repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types:
          - python
      - id: isort
        name: isort
        entry: isort
        language: system
        types:
          - python
      - id: black
        name: black
        entry: black
        language: system
        types:
          - python
