[default]
NAME = "Dev"
PORT = 8888
HOST = "localhost"
DEBUG = true
NASA_API_URL = "https://api.nasa.gov/"
NASA_API_KEY = {"api_key"="DEMO_KEY"}
APOD_URL_PATH = "planetary/apod"

[production]
NAME = "Prod"
DEBUG = false
